### ISSUE TITLE
用webbench测试效率很低

### ISSUE THREAD

**Issue by tomatowithpotato** [markparticle/WebServer#57]
我把服务器搭在一个腾讯云轻量级应用服务器上
一台二核的机子跑webbench

测试命令是 ./webbench -c 10000 -t 5 http://106.52.96.198:9999/

对于TinyWebServer
```shell
Speed=185652 pages/min, 349260 bytes/sec.
Requests: 15471 susceed, 0 failed.
```

对于当前项目
```shell
Speed=9600 pages/min, 815102 bytes/sec.
Requests: 800 susceed, 0 failed.
```

足足20倍的差距，这差距也大得忒离谱了
这个项目不是TinyWebServer的c++版本吗，
虽然有些改动，可按理不该差距这么大啊，看起来更像是出了bug

有没有大佬能给小弟解答一下呢？？？？？

**Comment by InternetofThingsprogrammer** [comment]
????

**Comment by InternetofThingsprogrammer** [comment]
我测两个qps的差不多?社长那个qps是我测得的结果的10倍,我怎么测都测不到社长的qps

**Comment by tomatowithpotato** [comment]
> 我测两个qps的差不多?社长那个qps是我测得的结果的10倍,我怎么测都测不到社长的qps

能说下具体的结果和配置吗，不胜感激

**Comment by tomatowithpotato** [comment]
又用了nginx和其他服务器测了测，发现结果都很差
想了想，可能是腾讯云轻量级应用服务器做了什么限制，导致的这种情况
哎

**Comment by peng-yq** [comment]
我测的也很低，而且还很多failed，不管是tiny那个项目还是这个，很怪
