### ISSUE TITLE
登录和注册的时候在输入框填完之后点击确定，server就停止运行

### ISSUE THREAD

**Issue by laputae** [markparticle/WebServer#74]
不管是新建一个用户还是登录已有的用户，都会出现报错。
报错信息如下
server: ../code/http/httprequest.cpp:182: static bool HttpRequest::UserVerify(const string&, const string&, bool): Assertion `sql' failed.
已放弃 (核心已转储)

**Comment by laputae** [comment]
以下是我的电脑环境
gcc version 11.3.0 
Linux ubuntu 5.15.0-58-generic
Ubuntu 22.04.1 LTS
mysql  Ver 8.0.32-0ubuntu0.22.04.2 for Linux on x86_64 ((Ubuntu))

**Comment by tang-jiapeng** [comment]
@laputae 我也一样，兄弟你找到原因了吗

**Comment by laputae** [comment]
我找到原因了。具体是这样的，要把这个配置文件里的数据库名字改一下。

**Comment by laputae** [comment]
把main.cpp里面的默认的mysql配置的数据库名字改为你自己创建的数据库的名字。

**Comment by tang-jiapeng** [comment]
@laputae 知道了，谢谢

**Comment by SKYT8** [comment]
![image](https://github.com/markparticle/WebServer/assets/42812147/4b4e1b3f-4cdc-4f83-8494-5979d704bf04)
如图中第二行参数：第一个参数为电脑上的数据库用户名称，一般是root，也可以是自己创建的一个用户；第二个参数是数据库的密码；第三个参数是你在root用户下创建的数据库名称；

**Comment by Alvahappy** [comment]
![image](https://github.com/markparticle/WebServer/assets/30755698/afeabf99-d922-442d-af77-bf0066679e68)
![image](https://github.com/markparticle/WebServer/assets/30755698/f8e4ac5d-1e23-4f40-9e87-788c9a3ea7a6)
你好，上面是我查到的数据库的用户名和密码。然后我把代码中的mysql配置参数也改了，还是有同样的问题，能帮忙看一下吗？

**Comment by laputae** [comment]
你在命令行中看到的密码是MD5哈希之后的密码，不是原始的。我建议重新设置一下密码。

**Comment by Study-gui** [comment]
博主，我改了，还是同样的问题!

**Comment by Kgksdt** [comment]
> 博主，我改了，还是同样的问题!
尝试用root开
