### ISSUE TITLE
浏览器访问时出现403禁止访问错误应该怎么解决

### ISSUE THREAD

**Issue by fragrant915** [markparticle/WebServer#82]

**Comment by HeartsRider** [comment]
我也是这个错误，我是部署在腾讯云服务器上，请问你解决了吗？

**Comment by fragrant915** [comment]
> 

修改main函数中对应的参数

**Comment by fragrant915** [comment]
我这边通过修改main函数中对应的参数已解决问题






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "markparticle/WebServer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月30日(星期天) 下午5:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [markparticle/WebServer] 浏览器访问时出现403禁止访问错误应该怎么解决 (Issue #82)





 
我也是这个错误，我是部署在腾讯云服务器上，请问你解决了吗？

**Comment by jammy-6** [comment]
这个是你使用https协议导致的，因为对请求的资源路径加密了，服务器无法正确返回对应资源，改成http就好了
